2023-12-03 14:37:22 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AA64B02DA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2023-12-03 14:37:22 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AA64B02E90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2023-12-03 14:37:22 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AA64B03C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2023-12-03 14:37:22 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AA64B01C90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2023-12-03 14:37:22 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AA64C6E3E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2023-12-03 14:37:22 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AA64C6E230>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
